name: My Workflow

on: 
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-latest
    env:
      # Setting an environment variable with the value of a configuration variable
      env_var: "${{ vars.PRIME_123 }}"
    steps:
    - name: Run build
      run: |
        echo "Running build..."
        echo "${{ env.env_var }}"
      
