name: My Workflow

on: 
  workflow_dispatch:
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.AUTOTEST_PRIME_123 }}

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Run build
      run: |
        echo "Running build..."
        echo "${{ env.env_var }}"
      
