name: My Workflow

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    environment: AUTOTEST
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Echo secret
      run: |
        echo "PRIME_PASS secret: ${{ secrets.PRIME_PASS }}"
    
    - name: Run build
      run: |
        echo "Running build..."
        echo "$PRIME_PASS"
        #echo "${{ env:PRIME_123 }}"
        echo "${{ AUTOTEST:PRIME_123 }}"
        echo "${{ secrets.PRIME_PASS }}"
        
