name: test

on:
  workflow_dispatch:
    inputs:
      filename:
        description: Name of json file
        required: true

jobs:
  build1:
    strategy:
      max-parallel: 1
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: JSON to variables
        uses: rgarcia-phi/json-to-variables@v1.1.0
        with:
          filename: '${{ github.event.inputs.filename }}'
          prefix: json
          masked: false
      
      - name: Show output
        run: echo "The time was ${{ env.json_value }}, ${{ env.json_array_0_value }}, ${{ env.json_obj_value1 }}"

  build2:
    runs-on: windows-latest
    needs: build1
    steps:
      - uses: actions/checkout@v2
      
      - name: Show output
        run: echo "The time was ${{ env.json_value }}, ${{ env.json_array_0_value }}, ${{ env.json_obj_value1 }}"
      
      - name: Update package.json version
        uses: jossef/action-set-json-field@v2
        with:
          file: test.json
          field: 'obj.value'
          value: 1001
      
      - name: Update package.json version
        uses: jossef/action-set-json-field@v2
        with:
          file: test.json
          field: 'array.0.value'
          value: 1002
      
      - name: Show output
        run: echo "The time was ${{ env.json_value }}, ${{ env.json_array_0_value }}, ${{ env.json_obj_value1 }}"
      
      - name: Create report file
        run: echo %date% >report.txt
      
      - name: Commit report
        run: |
          git config --global user.name 'shinoharat4'
          git config --global user.email 'shinoharat4@gmail.com'
          git commit -am "Automated report"
          git push
          
